/** ----------------------------------------------------------------------------------------------------
* 
*	This code was automatically generated by the UFT Developer Application Model code generator.
*
*	Changes to this file may cause incorrect behavior and will be lost 
*	when the code is regenerated.
*
*   ----------------------------------------------------------------------------------------------------
*/

package appmodel;
 
import com.hp.lft.sdk.*;

public class Sapphire extends AppModelBase{

	public Sapphire() {
		
	}

}